apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      imagePullSecrets:
      - name: artifact-registry-creds
      containers:
      - name: binarycalculator
        image: us-central1-docker.pkg.dev/sofe3290-lab3-p1-100792709/sofe3980u/binarycalculator
        ports:
        - containerPort: 8080
